before_script:
  - sudo yum install epel-release
  - sudo yum install nodejs
  - npm --version
  - node --version

stages:
  - install
  - deploy

install_job:
  stage: install
  script:
    - npm install

deploy_job:
  stage: deploy
  only:
    - master
  script:
    - npm install
    - npm run deploy
