before_script:
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash
  - export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
  - nvm --version
  - nvm install

stages:
  - install
  - deploy

install_job:
  stage: install
  script:
    - npm install

deploy_job:
  stage: deploy
  only:
    - master
  script:
    - npm install
    - npm run deploy
