image: nhsbsa/docker-centos-iac:latest

before_script:
  - export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which javac))))
  - export JRE_HOME=$(dirname $(dirname $(readlink -f $(which javac))))/jre
  - export GITLAB_API_ENDPOINT=https://gitlab00.node.consul/api/v3
  - export GITLAB_API_PRIVATE_TOKEN=e_ehRp9rc6EZADVBu6Pz
  - printenv | sort
  - java -version
  - eval "$(rbenv init -)"
  - ruby -v
  - git clone git@${CI_GIT_HOST}:devops/bsa-ci.git
  - (cd bsa-ci && bundle install)
  - eval $(ssh-agent -s)
  - ssh-add /root/.ssh/*id_rsa
  - sudo yum -y install epel-release
  - sudo yum -y install nodejs
  - npm --version
  - node --version

stages:
  - install
  - deploy

install_job:
  stage: install
  script:
    - npm install

deploy_job:
  stage: deploy
  only:
    - master
  script:
    - npm install
    - npm run deploy
    - bsa-ci/create_release_candidate.rb --verbose
  tags:
    - build

# Create:RC:
#   stage: build
#   only:
#     - master
#   script:
#     - bsa-ci/create_release_candidate.rb --verbose
#   tags:
#     - build

# release job
# for every release* branch:
# perform maven install and deploy:deploy
Binary:Push:
  stage: deploy
  only:
    - /^rc.*$/
  script:
    # mvn install to compile, test and qa changes
    # then deploy:deploy to push artifacts up to binary repo
    - mvn -B -DrepoUrl=$REPO_URL -DaltDeploymentRepository=bsa-rc::default::$REPO_URL/bsa-rc clean install deploy:deploy
  tags:
    - build
