image: nhsbsa/docker-centos-iac:latest

before_script:
  - eval $(ssh-agent -s)
  - ssh-add /root/.ssh/*id_rsa
  - sudo yum -y install epel-release
  - sudo yum -y install nodejs
  - npm --version
  - node --version

stages:
  - install
  - deploy

install_job:
  stage: install
  script:
    - npm install

deploy_job:
  stage: deploy
  only:
    - master
  script:
    - npm install
    - npm run deploy
    - mvn -B -DrepoUrl=$REPO_URL -DaltDeploymentRepository=bsa-rc::default::$REPO_URL/bsa-rc clean install deploy:deploy
